name: Release
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-manager:
    uses: ./.github/workflows/build-manager.yml
    secrets: inherit

  release:
    needs:
      - build-manager
    runs-on: ubuntu-latest
    steps:
      - name: Download Manager artifacts (release only)
        uses: actions/download-artifact@v8
        with:
          pattern: "*-release"
          merge-multiple: true
          path: manager

      - name: Display structure of downloaded files
        run: ls -R

      - name: Release
        uses: softprops/action-gh-release@v3
        with:
          files: manager/*.apk
